Repository syphon-org/syphon, pull requests merged in 2021-07, with the labels that each got.

#274 Theme refactor (attempt 2)
  lib/global/themes.dart
  lib/global/values.dart
  lib/main.dart
  lib/storage/middleware.dart
  lib/store/settings/actions.dart
  lib/store/settings/reducer.dart
  lib/store/settings/selectors.dart
  lib/store/settings/state.dart
  lib/store/settings/theme-settings/model.dart
  lib/store/settings/theme-settings/selectors.dart
  lib/views/home/chat/chat-detail-message-screen.dart
  lib/views/home/chat/chat-screen.dart
  lib/views/home/chat/widgets/message-list.dart
  lib/views/home/groups/group-create-public-screen.dart
  lib/views/home/groups/group-create-screen.dart
  lib/views/home/groups/invite-users-screen.dart
  lib/views/home/home-screen.dart
  lib/views/home/profile/profile-screen.dart
  lib/views/home/search/search-groups-screen.dart
  lib/views/home/search/search-rooms-screen.dart
  lib/views/home/search/search-users-screen.dart
  lib/views/home/settings/settings-screen.dart
  lib/views/home/settings/settings-theming-screen.dart
  lib/views/intro/login/login-screen.dart
  lib/views/intro/signup/loading-screen.dart
  lib/views/widgets/avatars/avatar-app-bar.dart
  lib/views/widgets/avatars/avatar.dart
  lib/views/widgets/containers/card-section.dart
  lib/views/widgets/containers/ring-actions.dart
  lib/views/widgets/messages/message.dart
Labels: bugfix, ready for review, refactoring

#280 [bugfix] SSO + User/Pass Flows
  ios/Runner.xcodeproj/project.pbxproj
  lib/global/dimensions.dart
  lib/global/libs/matrix/auth.dart
  lib/global/platform.dart
  lib/storage/index.dart
  lib/store/auth/actions.dart
  lib/store/auth/homeserver/model.dart
  lib/store/auth/selectors.dart
  lib/store/crypto/actions.dart
  lib/store/crypto/storage.dart
  lib/store/rooms/actions.dart
  lib/store/sync/actions.dart
  lib/views/home/profile/profile-screen.dart
  lib/views/home/settings/advanced-settings-screen.dart
  lib/views/home/settings/settings-storage-screen.dart
  lib/views/intro/intro-screen.dart
  lib/views/intro/login/forgot/widgets/PagePasswordReset.dart
  lib/views/intro/login/login-screen.dart
  lib/views/intro/search/search-homeserver-screen.dart
  lib/views/intro/signup/signup-screen.dart
  lib/views/intro/signup/widgets/StepHomeserver.dart
  lib/views/intro/signup/widgets/StepUsername.dart
  lib/views/widgets/appbars/appbar-chat.dart
  lib/views/widgets/buttons/button-outline.dart
  lib/views/widgets/buttons/button-text.dart
  lib/views/widgets/captcha.dart
  lib/views/widgets/modals/modal-image-options.dart
  pubspec.yaml
  version.txt
Labels: bugfix

#285 [bugfix] Theme Issues
  lib/store/settings/actions.dart
  lib/store/settings/theme-settings/selectors.dart
  lib/views/home/settings/settings-theming-screen.dart
  lib/views/intro/login/login-screen.dart
  lib/views/navigation.dart
  lib/views/widgets/containers/menu-rounded.dart
  lib/views/widgets/containers/ring-actions.dart
  pubspec.lock
  pubspec.yaml
Labels: bugfix

#298 [fixes] Various Issues Batch
  assets/copy.md
  lib/cache/index.dart
  lib/global/strings.dart
  lib/global/themes.dart
  lib/main.dart
  lib/storage/index.dart
  lib/store/events/model.dart
  lib/store/events/redaction/model.dart
  lib/store/index.dart
  lib/store/search/actions.dart
  lib/store/settings/theme-settings/selectors.dart
  lib/store/sync/actions.dart
  lib/store/user/selectors.dart
  lib/views/home/chat/chat-detail-screen.dart
  lib/views/home/chat/chat-screen.dart
  lib/views/home/chat/widgets/chat-input.dart
  lib/views/home/chat/widgets/message-list.dart
  lib/views/home/groups/group-create-public-screen.dart
  lib/views/home/groups/invite-users-screen.dart
  lib/views/home/profile/profile-screen.dart
  lib/views/home/profile/profile-user-screen.dart
  lib/views/home/search/search-groups-screen.dart
  lib/views/home/search/search-users-screen.dart
  lib/views/home/settings/advanced-settings-screen.dart
  lib/views/home/settings/settings-chats-screen.dart
  lib/views/home/settings/settings-theming-screen.dart
  lib/views/intro/intro-screen.dart
  lib/views/intro/login/login-screen.dart
  lib/views/prelock.dart
  lib/views/syphon.dart
  lib/views/widgets/avatars/avatar.dart
  lib/views/widgets/containers/mount-widget.dart
  lib/views/widgets/dialogs/dialog-color-picker.dart
  lib/views/widgets/dialogs/dialog-confirm.dart
  lib/views/widgets/lists/list-item-user.dart
  lib/views/widgets/lists/list-item.dart
  lib/views/widgets/messages/message.dart
  lib/views/widgets/modals/modal-user-details.dart
Labels: bugfix, enhancement

#305 German Translations
  assets/translations/de.json
  assets/translations/en.json
  lib/global/formatters.dart
  lib/store/settings/actions.dart
  lib/views/syphon.dart
  pubspec.yaml
Labels: translation

#316 [Refactoring] Replace default string value 'matrix.org' by global const Values.homeserverDefault
  lib/global/formatters.dart
  lib/global/libs/matrix/auth.dart
  lib/global/libs/matrix/devices.dart
  lib/global/libs/matrix/encryption.dart
  lib/global/libs/matrix/events.dart
  lib/global/libs/matrix/media.dart
  lib/global/libs/matrix/notifications.dart
  lib/global/libs/matrix/rooms.dart
  lib/global/libs/matrix/search.dart
  lib/global/libs/matrix/user.dart
  lib/store/auth/actions.dart
  lib/store/auth/state.dart
  lib/views/intro/login/forgot/widgets/PageEmailVerify.dart
Labels: refactoring

#312 Minor updates to the nl.json file
  assets/translations/nl.json
Labels: translation
