Repository syphon-org/syphon, pull requests merged in 2021-08, with the labels that each got.

#318 Update of German translation (de.json)
  assets/translations/de.json
Labels: translation

#323 [feature] Customize FAB Settings
  lib/storage/middleware.dart
  lib/store/settings/actions.dart
  lib/store/settings/reducer.dart
  lib/store/settings/theme-settings/model.dart
  lib/store/settings/theme-settings/selectors.dart
  lib/views/home/chat/chat-screen.dart
  lib/views/home/chat/widgets/message-list.dart
  lib/views/home/home-screen.dart
  lib/views/home/settings/settings-screen.dart
  lib/views/home/settings/settings-theme-screen.dart
  lib/views/intro/login/login-screen.dart
  lib/views/navigation.dart
  lib/views/widgets/containers/fabs/fab-bar-expanding.dart
  lib/views/widgets/containers/fabs/fab-circle-expanding.dart
  lib/views/widgets/containers/fabs/fab-ring.dart
  lib/views/widgets/messages/message-typing.dart
  lib/views/widgets/messages/message.dart
  lib/views/widgets/modals/modal-user-details.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, a11y

#326 [fix] Decryption Issues
  lib/cache/serializer.dart
  lib/global/strings.dart
  lib/storage/constants.dart
  lib/storage/index.dart
  lib/storage/middleware.dart
  lib/store/auth/middleware.dart
  lib/store/auth/state.dart
  lib/store/crypto/actions.dart
  lib/store/crypto/events/actions.dart
  lib/store/crypto/events/selectors.dart
  lib/store/crypto/keys/actions.dart
  lib/store/crypto/reducer.dart
  lib/store/crypto/state.dart
  lib/store/crypto/storage.dart
  lib/store/events/actions.dart
  lib/store/events/messages/actions.dart
  lib/store/events/messages/model.dart
  lib/store/events/model.dart
  lib/store/events/receipts/storage.dart
  lib/store/events/reducer.dart
  lib/store/events/selectors.dart
  lib/store/events/state.dart
  lib/store/events/storage.dart
  lib/store/rooms/actions.dart
  lib/store/rooms/room/model.dart
  lib/store/sync/actions.dart
  lib/views/home/chat/chat-screen.dart
  lib/views/home/home-screen.dart
  lib/views/intro/intro-screen.dart
Labels: bugfix

#324 [fix] Various Issues Batch
  assets/translations/en.json
  assets/translations/pt.json
  lib/cache/serializer.dart
  lib/global/formatters.dart
  lib/global/libs/matrix/encryption.dart
  lib/global/libs/matrix/user.dart
  lib/global/strings.dart
  lib/global/values.dart
  lib/storage/constants.dart
  lib/storage/index.dart
  lib/storage/middleware.dart
  lib/store/alerts/actions.dart
  lib/store/auth/actions.dart
  lib/store/auth/middleware.dart
  lib/store/auth/reducer.dart
  lib/store/auth/state.dart
  lib/store/crypto/actions.dart
  lib/store/crypto/events/actions.dart
  lib/store/crypto/events/selectors.dart
  lib/store/crypto/keys/actions.dart
  lib/store/crypto/keys/selectors.dart
  lib/store/crypto/reducer.dart
  lib/store/crypto/state.dart
  lib/store/crypto/storage.dart
  lib/store/events/actions.dart
  lib/store/events/messages/actions.dart
  lib/store/events/messages/model.dart
  lib/store/events/model.dart
  lib/store/events/receipts/storage.dart
  lib/store/events/reducer.dart
  lib/store/events/selectors.dart
  lib/store/events/state.dart
  lib/store/events/storage.dart
  lib/store/rooms/actions.dart
  lib/store/rooms/room/model.dart
  lib/store/settings/actions.dart
  lib/store/settings/devices-settings/selectors.dart
  lib/store/sync/actions.dart
  lib/views/home/chat/chat-screen.dart
  lib/views/home/home-screen.dart
  lib/views/home/settings/password/password-update-screen.dart
  lib/views/home/settings/settings-chats-screen.dart
  lib/views/home/settings/settings-devices-screen.dart
  lib/views/home/settings/settings-privacy-screen.dart
  lib/views/home/settings/settings-screen.dart
  lib/views/intro/intro-screen.dart
  lib/views/intro/login/forgot/widgets/PageEmailVerify.dart
  lib/views/intro/signup/widgets/StepCaptcha.dart
  lib/views/syphon.dart
  lib/views/widgets/lists/list-item.dart
  pubspec.yaml
Labels: bugfix, enhancement

#334 [fix] Decryption Issues
  fastlane/metadata/android/en-US/changelogs/230.txt
  lib/cache/middleware.dart
  lib/global/libs/matrix/encryption.dart
  lib/storage/middleware.dart
  lib/store/auth/actions.dart
  lib/store/crypto/actions.dart
  lib/store/crypto/events/actions.dart
  lib/store/crypto/keys/selectors.dart
  lib/store/crypto/reducer.dart
  lib/store/crypto/state.dart
  lib/store/events/messages/model.dart
  lib/store/sync/background/parsers.dart
  lib/store/sync/background/service.dart
  lib/views/home/chat/chat-screen.dart
  lib/views/home/settings/settings-privacy-screen.dart
  pubspec.yaml
  version.txt
Labels: bugfix
