Repository syphon-org/syphon, pull requests merged in 2021-02, with the labels that each got.

#223 Android system UI tweaks
  android/app/build.gradle
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  lib/main.dart
  lib/store/settings/actions.dart
Labels: ready for review

#229 [fix] Batched Fixes 0.1.6+3
  android/app/src/main/res/values/styles.xml
  assets/translations/en.json
  ios/Flutter/.last_build_id
  lib/cache/serializer.dart
  lib/cache/storage.dart
  lib/global/libs/matrix/rooms.dart
  lib/global/strings.dart
  lib/global/themes.dart
  lib/global/values.dart
  lib/main.dart
  lib/storage/constants.dart
  lib/storage/index.dart
  lib/storage/middleware.dart
  lib/store/alerts/actions.dart
  lib/store/alerts/middleware.dart
  lib/store/auth/actions.dart
  lib/store/crypto/actions.dart
  lib/store/crypto/events/actions.dart
  lib/store/rooms/actions.dart
  lib/store/rooms/room/model.dart
  lib/store/search/actions.dart
  lib/store/settings/actions.dart
  lib/store/settings/reducer.dart
  lib/store/settings/selectors.dart
  lib/store/settings/state.dart
  lib/store/settings/storage.dart
  lib/store/user/selectors.dart
  lib/views/behaviors.dart
  lib/views/home/chat/details-message.dart
  lib/views/home/chat/index.dart
  lib/views/home/groups/group-create-public.dart
  lib/views/home/groups/group-create.dart
  lib/views/home/index.dart
  lib/views/home/profile/index.dart
  lib/views/home/search/search-groups.dart
  lib/views/home/search/search-rooms.dart
  lib/views/home/search/search-users.dart
  lib/views/home/settings/chats.dart
  lib/views/home/settings/devices.dart
  lib/views/home/settings/index.dart
  lib/views/home/settings/password/index.dart
  lib/views/home/settings/privacy.dart
  lib/views/home/settings/theming.dart
  lib/views/intro/third.dart
  lib/views/login/forgot/password-reset-email.dart
  lib/views/login/forgot/password-reset.dart
  lib/views/login/index.dart
  lib/views/signup/index.dart
  lib/views/signup/loading.dart
  lib/views/signup/verification.dart
  lib/views/widgets/appbars/appbar-chat.dart
  lib/views/widgets/appbars/appbar-search.dart
  lib/views/widgets/avatars/avatar.dart
  lib/views/widgets/lists/list-item.dart
  lib/views/widgets/messages/message.dart
  lib/views/widgets/modals/modal-user-details.dart
Labels: bug

#231 message reply fixes
  lib/global/libs/matrix/events.dart
  lib/store/crypto/events/actions.dart
  lib/store/events/actions.dart
  lib/store/events/messages/actions.dart
Labels: bug

#235 [0.1.7] Touch Up Release
  ios/Flutter/.last_build_id
  ios/Podfile.lock
  lib/cache/serializer.dart
  lib/cache/storage.dart
  lib/global/dimensions.dart
  lib/global/libs/matrix/auth.dart
  lib/global/libs/matrix/devices.dart
  lib/global/libs/matrix/encryption.dart
  lib/global/libs/matrix/events.dart
  lib/global/libs/matrix/index.dart
  lib/global/libs/matrix/notifications.dart
  lib/global/libs/matrix/rooms.dart
  lib/global/libs/matrix/search.dart
  lib/global/libs/matrix/user.dart
  lib/global/platform.dart
  lib/global/strings.dart
  lib/global/values.dart
  lib/main.dart
  lib/storage/index.dart
  lib/store/auth/actions.dart
  lib/store/auth/homeserver/actions.dart
  lib/store/crypto/actions.dart
  lib/store/events/actions.dart
  lib/store/events/messages/actions.dart
  lib/store/events/reducer.dart
  lib/store/events/selectors.dart
  lib/store/index.dart
  lib/store/rooms/actions.dart
  lib/store/rooms/room/model.dart
  lib/store/rooms/room/selectors.dart
  lib/store/settings/actions.dart
  lib/store/settings/chat-settings/sort-order/model.dart
  lib/store/settings/reducer.dart
  lib/store/settings/state.dart
  lib/store/sync/actions.dart
  lib/store/user/actions.dart
  lib/store/user/reducer.dart
  lib/store/user/selectors.dart
  lib/views/home/chat/chat-input.dart
  lib/views/home/chat/index.dart
  lib/views/home/chat/message-list.dart
  lib/views/home/index.dart
  lib/views/home/profile/index.dart
  lib/views/home/search/search-groups.dart
  lib/views/home/settings/chats.dart
  lib/views/home/settings/index.dart
  lib/views/login/index.dart
  lib/views/widgets/messages/message.dart
  lib/views/widgets/modals/modal-user-details.dart
  pubspec.yaml
Labels: bug, enhancement, wip
