Repository syphon-org/syphon, pull requests merged in 2022-04, with the labels that each got.

#672 [fix] Missing closing brace
  lib/views/home/settings/settings-privacy-screen.dart
Labels: bug, p0

#674 [chore] update PR template to add linting
  .github/pull_request_template.md
Labels: documentation

#670 [feature] add English (🇬🇧) translation
  assets/translations/en-gb.json
Labels: translation

#668 [fix] notification background thread proxy
  lib/global/connectivity.dart
  lib/store/settings/actions.dart
  lib/store/settings/proxy-settings/model.dart
  lib/store/sync/actions.dart
  lib/store/sync/background/service.dart
  lib/views/home/chat/media-full-screen.dart
Labels: bug
